# Generated by Django 6.0.2 on 2026-05-27 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_descarga', models.CharField(choices=[('TIPN', '1 - TIPN | Porto Nacional'), ('TIP', '2 - TIP | Palmeirante'), ('TIUB', '3 - TIUB | Uberaba'), ('TRO', '4 - TRO | Terminal Rumo Rondonópolis'), ('TSS', '5 - TSS | Terminal Rumo São Simão'), ('TRV', '6 - TRV | Terminal Rumo Rio Verde'), ('TGG', '7 - TGG | Terminal de Guarujá'), ('BRF_RV', '8 - BRF - Rio Verde'), ('BRF_UB', '9 - BRF - Uberlândia'), ('BRF_CN', '10 - BRF - Campos Novos'), ('BRF_AM', '11 - BRF - Arroio do Meio'), ('BRF_CH', '12 - BRF - Chapecó'), ('BUNGE', '13 - Bunge - Maringá'), ('SFS', '14 - São Francisco do Sul'), ('TGRAO', '15 - Terminal T-Grão'), ('ROLANDIA', '16 - Rolândia'), ('PINHALZINHO', '17 - Pinhalzinho'), ('PARANAGUA', '18 - Paranaguá'), ('BARCARENA', '19 - Barcarena'), ('ITAITUBA', '20 - Itaituba'), ('OUTRO', '21 - Outro')], max_length=30)),
                ('placa_cavalo', models.CharField(max_length=10)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_opcao_1', models.DateField()),
                ('horario_opcao_1', models.TimeField()),
                ('data_opcao_2', models.DateField(blank=True, null=True)),
                ('horario_opcao_2', models.TimeField(blank=True, null=True)),
                ('data_opcao_3', models.DateField(blank=True, null=True)),
                ('horario_opcao_3', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado'), ('FINALIZADO', 'Finalizado')], default='PENDENTE', max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='agendamentos.motorista')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
