# Generated by Django 6.0.2 on 2026-06-01 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['data_cadastro'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data_ultima_alteracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='mensagem_operacional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='motivo_alteracao_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='usuario_ultima_alteracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_alterados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='placa_cavalo',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em Análise'), ('FINALIZADO', 'Finalizado')], db_index=True, default='ABERTO', max_length=20),
        ),
    ]
